api_version: 3
name: DxD_FL
description: DxD Federated Learning project yaml file

participants:
  - name: 13.212.96.191
    type: server
    org: DxD
    fed_learn_port: 8004
    admin_port: 8005
  - name: DxD_site_1
    type: client
    org: DxD_1
  - name: DxD_site_2
    type: client
    org: DxD_2
  - name: DxD_site_3
    type: client
    org: DxD_3
  - name: admin@dxd.com
    type: admin
    org: DxD
    role: DxD_project_admin
  - name: admin2@dxd.com
    type: admin
    org: DxD
    role: DxD_project_admin

builders:
  - path: nvflare.lighter.impl.workspace.WorkspaceBuilder
    args:
      template_file: master_template.yml
  - path: nvflare.lighter.impl.template.TemplateBuilder
  - path: nvflare.lighter.impl.static_file.StaticFileBuilder
    args:
      config_folder: config

      overseer_agent:
        path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
        overseer_exists: false
        args:
          sp_end_point: 13.212.96.191:8004:8005

  - path: nvflare.lighter.impl.cert.CertBuilder
  - path: nvflare.lighter.impl.signature.SignatureBuilder
